### ISSUE TITLE
start_server failed

### ISSUE THREAD

**Issue by TylerPickstock** [Spafbi/simplified-miscreated-server-setup#1]
When i run the 'start_server' i go through the instructions but when it starts downloading the content it fails straight away. Why?

**Comment by TylerPickstock** [comment]
![4771b25ca892eb01617d0cf1d2377869](https://user-images.githubusercontent.com/50087075/56870824-289ce200-6a0d-11e9-8914-79ce0330a9f4.png)

**Comment by Spafbi** [comment]
Per the instructions:

*"It's best to keep the path to where you want to install the server short, with no spaces, and using only ASCII characters."*

Your path has a space in it.
