### ISSUE TITLE
Server second launch

### ISSUE THREAD

**Issue by lviar** [Spafbi/simplified-miscreated-server-setup#4]
Hello! I want to thank you for doing such an easy way to create server. But i hit some problems. 
For the first launch of server (using start_server.cmd) i created one and entered. Playing some time i exit and stopped server. Next time i wanted to play on it, start_server.cmd is not starting. Just closing. I created new directory and uce cmd there. It started server again but it was empty.
How can i launch my first server again?

**Comment by Spafbi** [comment]
That's definitely very strange behavior as I haven't seen it before. As this issue is a little old, now, make sure you have the latest version of the script and try again. If you are still having issues, create another "issue" and I'll give you more instructions for troubleshooting.
